### ISSUE TITLE
Checkout page header issue

### ISSUE THREAD

**Issue by kitays** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#64]
Once I installed the plugin, the header of the checkout page does not show up, neither the image assigned to the page.

Any idea? I'm also using Elementor.
Thanks a lot

**Comment by kitays** [comment]
now i installed the latest version from this repo, the header is back, but I cannot see the edit icon to enter the API credentials

**Comment by sofyansitorus** [comment]
@kitays It seems your issue similar with the existing one which is fixed by re-install the plugin. Could you please check on this one issue: https://wordpress.org/support/topic/cant-enter-api-pencil-icon-not-visible/

**Comment by sofyansitorus** [comment]
@kitays I guess you install this plugin not through the WordPress plugin repository?

**Comment by kitays** [comment]
Hi! Thanks for your reply
That issue I was able to fix, but I still have this one:

once I installed the plugin, the header of the checkout page does not show
up, neither the image assigned to the page.

Any idea? I’m also using Elementor.
Thanks a lot



Leo Kitay

[image: photo-logo]

**Comment by kitays** [comment]
@sofyansitorus hi! thanks for your reply.
That issue related to the edit icon, I was able to fix, but I still have this one:

once I installed the plugin, the header of the checkout page does not show up, neither the image assigned to the page.

Any idea? I’m also using Elementor.
Thanks a lot

**Comment by sofyansitorus** [comment]
@kitays Not sure how, but this plugin supposes has nothing to do with the header area. I don't think this plugin can cause any layout element issue. Even there is NO CSS loaded in tho frontend by this plugin. It just loads a single JS file which doing nothing special except trying to create address line 2 field in the shipping calculator on the cart page, below is the JS file loaded in the frontend.

https://github.com/sofyansitorus/WooCommerce-Shipping-Distance-Matrix/blob/master/assets/src/js/frontend.js

Could you please check is there any JS error printed in the browser console while on the checkout page?

**Comment by kitays** [comment]
I'm trying to get the output.
look what Paul from Elementor said:

On inspecting the page it is noticed that there are console errors, which might be causing the issue.
Screenshot: https://prnt.sc/sdjkmg

Since the issue started after installing Wooreer, it could be possible that this plugin is not working well with other plugins including Elementor and other addons.

It is also noticed that the Wooreer plugin is causing JS error on other pages too.
Screenshot: https://prnt.sc/sdjl1q

Please deactivate this plugin and report the error to the Wooreer plugin support.

**Comment by sofyansitorus** [comment]
Well yeah, there is an error in JS console. But the funny thing is the error because WooReer trying to enqueue/load **underscore.js** which is WordPress standard JS library, but unfortunately, there is a genius developer messing around and blocking it. I am sorry I will not accommodate this. There is nothing wrong with how is WooReer plugin load the js assets. A good developer should not be messing around with WordPress standard JS library. There is many plugins/themes depending on it.

Default Scripts and JS Libraries Included and Registered by WordPress as follow:

https://developer.wordpress.org/reference/functions/wp_enqueue_script/

**Comment by kitays** [comment]
Sorry, but i didn't mess around with standard JS lib, in fact I didn't touch it.
Why do you think the issue came from there?
Thanks
L

**Comment by sofyansitorus** [comment]
@kitays Sorry, I did not tell you messing around the standard JS lib, but I believe it somewhere in any files of the plugins and themes you used. 

Why I can be sure? The error showing that `_` variable is undefined.  That variable is a part of Underscore.js which is loaded along with `wp-util` JS lib, and that variable supposes to exist in the `window` object scope if there is no existing code that messing around with standard JS lib.

My only suggestion is please try to add extra hooks to enqueue the underscore.js lib manually, not sure it will work but worth to give a shot.

**Comment by sofyansitorus** [comment]
Or another solution is by dequeuing the `wcsdm-frontend` js file when not on the cart page by adding the following PHP code to your functions.php theme file:

```
function wcsdm_dequeue_frontend_script() {
    if ( function_exists( 'is_cart' ) && is_cart() ){
        return;
    }

    wp_dequeue_script( 'wcsdm-frontend' );
}
add_action( 'wp_print_scripts', 'wcsdm_dequeue_frontend_script', 999 );

```

**Comment by kitays** [comment]
Thanks a lot!!! it works you rock!
Let me know if I can help you out w something else.
R
L

**Comment by sofyansitorus** [comment]
@kitays Glad to hear it works. Perhaps you can help me to increase the rating of this plugin by submitting a rating and review here: https://wordpress.org/plugins/wcsdm/#reviews
